version: '3'
services:
  mta-receive:
    container_name: mta-receive
    image: golang:1.17.1
    working_dir: /mta-test
    volumes:
      - ${PWD}:/mta-test
    environment:
      - SMTP_CONF=mta-receive.conf.json
    links:
      - mta-send
      - swaks-send
    command: sh -c "go run app/main.go"

  mta-send:
    container_name: mta-send
    image: golang:1.17.1
    working_dir: /mta-test
    volumes:
      - ${PWD}:/mta-test
    environment:
      - SMTP_CONF=mta-send.conf.json
    command: sh -c "go run app/main.go"

  swaks-send:
    container_name: swaks-send
    image: golang:1.17.1
    command: sh -c "apt-get update && apt-get install swaks -y && bash"
    stdin_open: true # -i
    tty: true        # -t

